language: node_js
jobs:
  include:
    - node_js: 8
    - node_js: 10
    - node_js: 12
    - node_js: 13
before_install:
  - npm install -g pnpm
install:
  - pnpm install
script: 
  - pnpm run bld-f
  - pnpm run bld-b