name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup pnpm
      run: npm install -g pnpm
    - name: Install dependencies
      run: pnpm install
    - name: Build frontend
      run: pnpm run bld-f
    - name: Build backend
      run: pnpm run bld-b
